### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by ppihus** [igorpecovnik/Debian-micro-home-server#2]
Can't seem to find a decent way to uninstall this. ISPConfig originally has uninstall.php script included, however that doesn't seem to work with this repo.

**Comment by igorpecovnik** [comment]
The whole thing is complex and such things is usually hard to uninstall to perfectly clean state. Better to start from a clean system ... The ISPconfig is installed via their install script so if they provide some uninstall script it might even work. But I doubt they cover all their dependencies.
