### ISSUE TITLE
Softy allows to install stuff that's already installed

### ISSUE THREAD

**Issue by ThomasKaiser** [igorpecovnik/Debian-micro-home-server#5]
I would propose simple sanity checks for Softy as follows (should work with config files for the other daemons as well):

    [ -f /etc/samba/smb.conf ] || LIST+=( "Samba" "Windows compatible file sharing" "off" )
    [ "$family" = "Ubuntu" -o -f /etc/default/openmediavault ] || LIST+=( "OMV" "OpenMediaVault NAS solution" "off" )

**Comment by igorpecovnik** [comment]
https://github.com/igorpecovnik/Debian-micro-home-server/commit/fb587bdfb10b24c385b448839302929e757d7a2f
